export const data = [
  {
    id: 1,
    name: "Gondar",
    price: "$29",
    info: "Fasil Ghebbi is located in the Amhara National Regional State, in North Gondar Administrative Zone of the Federal Democratic Republic of Ethiopia. The serial property consists of eight components. Within the Fasil Ghebbi palace compound are: the Castle of Emperor Fasilidas, the Castle of Emperor Iyasu, the Library of Tzadich Yohannes; the Chancellery ofTzadichYohannes; the Castle of Emperor David, the Palace of Mentuab and Banqueting Hall of the Emperor Bekaffa. The remaining seven components are located in and around the city of Gondar: the Debre Berhan Selassie (Monastery and church); the Bath of Fasilidas; Kiddush Yohannes; Qusquam (Monastery and Church); Thermal Area; the Sosinios (also known as Maryam Ghemb); the Gorgora (Monastery and Church) and the Palace of Guzara.Between the thirteenth and seventeenth centuries, Ethiopian rulers moved their royal camps frequently. King Fasil (Fasilidas) settled in Gondar and established it as a permanent capital in 1636",
    image:
      "https://brilliant-ethiopia.imgix.net/gonder-castles-3.JPG?auto=format,enhance,compress&fit=crop&crop=entropy,faces,focalpoint&w=1200&h=0&q=30",
  },
  {
    id: 2,
    name: "Gishen mariam",
    price: "$32",
    info: "Gishen is one of the places of immense significance for Ethiopian Church and Ethiopian Orthodox Christians, perhaps even for Christianity itself. It has got a portion of the cross on which Jesus Christ is crucified is located.The Bible explicitly suggests that the first christian convert was the Ethiopian eunuch, written in Acts 8. Before the disciples of Jesus went outside of Israel to preach Christ, Philip the Evangelist happened to meet Ethiopian eunuch who posed questions about the Christian faith and Jesus Christ before he embraced Christianity. Later on, he came back Ethiopia and preached the faith. The originality of Christianity in Ethiopia and the Ethiopian church is partly attributed to that storyEthiopian Church teaching has it that the Cross on which Jesus was crucified continued to do miracles and heal patients after the ascension of Jesus Christ. Descendants of the establishment that crucified Jesus Christ were embarrassed about it so much so that they had to hid the cross ; dug deep, buried it and made the place where it was buried a dumping place. Sometime in the forth century, Empress Eleni , who was said to have spiritual guidance, started the search for it, located and uncovered it after excavation work. There after, the cross lived in Jerusalem for centuries and was later shared by the then powerful countries. That’s how Ethiopia got a piece of it. [adToAppearHere]",
    image:
      "https://d3i71xaburhd42.cloudfront.net/0aca89e1139940860fa39db9760bf6f676b5a706/5-Figure2-1.png",
  },
  {
    id: 3,
    name: "Lalibela",
    price: "$36",
    info: "In a mountainous region in the heart of Ethiopia, some 645 km from Addis Ababa, eleven medieval monolithic churches were carved out of rock. Their building is attributed to King Lalibela who set out to construct in the 12th century a ‘New Jerusalem’, after Muslim conquests halted Christian pilgrimages to the holy Land. Lalibela flourished after the decline of the Aksum Empire.There are two main groups of churches – to the north of the river Jordan: Biete Medhani Alem  (House of the Saviour of the World), Biete  Mariam (House of Mary), Biete  Maskal (House of the Cross), Biete Denagel (House of Virgins), Biete Golgotha Mikael (House of Golgotha Mikael); and to the south of the river, Biete Amanuel (House of Emmanuel), Biete Qeddus Mercoreus (House of St. Mercoreos), Biete Abba Libanos (House of Abbot Libanos), Biete Gabriel Raphael (House of Gabriel Raphael), and Biete Lehem (House of Holy Bread). The eleventh church, Biete Ghiorgis (House of St. George), is isolated from the others, but connected by a system of trenchesThe churches were not constructed in a traditional way but rather were hewn from the living rock of monolithic blocks. These blocks were further chiselled out, forming doors, windows, columns, various floors, roofs etc. This gigantic work was further completed with an extensive system of drainage ditches, trenches and ceremonial passages, some with openings to hermit caves and catacombs.Biete Medhani Alem, with its five aisles, is believed to be the largest monolithic church in the world, while Biete Ghiorgis has a remarkable cruciform plan. Most were probably used as churches from the outset, but Biete Mercoreos and Biete Gabriel Rafael may formerly have been royal residences. Several of the interiors are decorated with mural paintings.Near the churches, the village of Lalibela has two storey round houses, constructed of local red stone, and known as the Lasta Tukuls. These exceptional churches have been the focus of pilgrimage for Coptic Christians since the 12th century",
    image:
      "https://whc.unesco.org/uploads/thumbs/site_0018_0016-750-750-20151104173458.jpg",
  },
  {
    id: 4,
    name: "Debre Damo",
    price: "$34",
    info: "Debre Damo monastery is situated on an isolated mountain in northern part of Tigray. It is unique compared with most Ethiopian monasteries. Debre Damo was built, in the 6th century AD, with curved wood panels, painted ceilings and walls dedicated to the legend of Saint (Abune) Aregawi. The history of Debre Damo is centered on the Nine Saints who came to Ethiopia from Syria to spread Christianity in the Tigray region. One of them was Saint Aregawi who settled on the mountain of Debre Damo. The other eight saints settled around Tigray countryside and all have their own church named after them.Debre Damo is only accessible by climbing up by a rope, which is made of plaited leather, lowered from the cliffs, which visitors tie around their waist and are then pulled up by a monk at the top of the cliffs. It is only accessible to men and male animals. Women and even female animals are forbidden to set a foot into the monastery, and must remain under the cliffs and pray from there.",
    image: "https://martinplaut.files.wordpress.com/2021/02/debre-danos.jpg",
  },
  {
    id: 5,
    name: "Axsum",
    price: "$29",
    info: "Aksum or Axum is widely identified by the famous obelisks, or monolithic stelae . In ancient times, seven of these monoliths of granite stood together; but the biggest, the largest monolith ever made anywhere in the world - measuring over thirty-three metres (108 feet) and weighing about 500 tons - fell at some remote period in the past and now lies smashed on the ground to the right of the standing stelae. The second-largest stelae, about twenty-four metres (79 feet) high, also fell and was stolen during the Fascist Italian occupation on the personal orders of the dictator Mussolini. After 68 years It finally returned to Ethiopia and erected at its original place. The third-largest stelae, measuring twenty-three metres (75 feet), still stands in Axum.. In addition to the stelae in this part of Axum, the field also bears several tombs. Grave robbers plundered the royal spoils of the tombs centuries before archaeologists had the opportunity to preserve them. located at the west end of the stelae Park, this subterranean funerary complex is named after the false door carved over the access stairway in a style very similar to that of steles .it was Discovered in 1972 and is thought to date around the 4th century AD. Complex in structure, its stone blocks are also larger and more finely dressed than those found in some other tombs. Comprising an antechamber and inner chamber, it’s surrounded on three sides by a passage. The tomb was robbed in the past of all the precious goods it presumably contained. The so-called mausoleum has a monumental portal (hewn from a single slab of granite) marking the tomb’s entrance and is carved with the stelae’s curious false-door motifs. The portal leads into a passageway with 10 chambers. In total the tomb covers some 240 sq metres. ",
    image:
      "https://media.istockphoto.com/photos/obelisk-in-the-aksum-kingdom-ethiopia-picture-id186914973?k=20&m=186914973&s=612x612&w=0&h=NmTh_aJyS9iHRt4vF3waqf9pmVhDt5jNRePNQM3P67U=",
  },
];
export default data;